# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='next_page',
            field=models.IntegerField(default=0),
        ),
    ]
