# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_choice_next_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
