# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_page_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='name',
        ),
        migrations.AddField(
            model_name='page',
            name='page_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
