# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20170418_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='id',
        ),
        migrations.AlterField(
            model_name='page',
            name='page_id',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
