# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20170418_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='next_page',
            field=models.CharField(default='', max_length=20),
        ),
    ]
