# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20170419_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
