# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20170419_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='active_talent',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='choice',
            name='karma',
            field=models.IntegerField(default=0),
        ),
    ]
