# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20170421_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='consequence',
            field=models.CharField(default='', max_length=20),
        ),
    ]
